ktor:
  development: true
  deployment:
    port: 8080
  application:
    modules:
      - veeci.practicing.SerializationKt.configureSerialization
      - veeci.practicing.StatusPagesKt.configureStatusPages
      - veeci.practicing.WebsocketsKt.configureWebsockets
      - veeci.practicing.RoutingKt.configureRouting
