ktor:
  development: true
  deployment:
    port: 8080
  application:
    modules:
      - veeci.practicing.rts.SerializationKt.configureSerialization
      - veeci.practicing.rts.StatusPagesKt.configureStatusPages
      - veeci.practicing.rts.WebsocketsKt.configureWebsockets
      - veeci.practicing.rts.RoutingKt.configureRouting
